repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: "23.10.1"
    hooks:
      - id: black

  - repo: https://github.com/lucas-c/pre-commit-hooks-safety
    rev: "v1.3.2"
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args: [--max-line-length=88]
