version: "3.9"

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./source:/app/source
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3
