FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY config/requirements.txt config/
RUN pip install --no-cache-dir -r config/requirements.txt

COPY alembic.ini .
COPY source source

CMD alembic upgrade head && uvicorn source.main:app --host 0.0.0.0 --reload
